universe = vanilla
executable = build_gp_job.sh
arguments = $(MBs) $(MDp) $(CHAN)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = run_card_template.dat
output = logs/build_$(CHAN)_MBs$(MBs)_MDp$(MDp).$(Cluster).out
error  = logs/build_$(CHAN)_MBs$(MBs)_MDp$(MDp).$(Cluster).err
log    = logs/build.$(Cluster).log
request_cpus = 4
request_memory = 8GB
request_disk = 12GB
x509userproxy = /uscms_data/d3/murtazas/x509_proxy.pem
+ApptainerImage = "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel8"
queue MBs MDp CHAN from build_args.txt
